version: "3.9"

services:
  bittle:
    build:
      context: ..
      dockerfile: docker-deployments/DockerFile.dockerfile
      args:
        ACCEPT_EULA: "Y"
    container_name: bittlehrl-sim
    network_mode: "host"

    environment:
      ACCEPT_EULA: "Y"
      NUM_ENVS: 8
      MAX_ITERS: 15
      #DISPLAY: ${DISPLAY}
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
      OMNI_KIT_ALLOW_ROOT: 1
      TERM: xterm
      PYTHONPATH: /IsaacLab/source:/BittleHRL/source/BittleHRL

    volumes:
      - ../:/BittleHRL:rw                # mount full project
      #- /tmp/.X11-unix:/tmp/.X11-unix:rw
      #- $HOME/.Xauthority:/root/.Xauthority:rw
      - ~/.cache/ov:/root/.cache/ov:rw
      - ~/.nucleus:/root/.nucleus:rw
      - ./checkpoints:/BittleHRL/checkpoints:rw

    runtime: nvidia
    stdin_open: true
    tty: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    
    entrypoint: ["/BittleHRL/docker-deployments/entrypoint.sh"]
